export const COUNTRY_MAP: Record<string, { name: string; flag: string }> = {
  AF: { name: "Afghanistan",            flag: "🇦🇫" },
  AL: { name: "Albania",                flag: "🇦🇱" },
  DZ: { name: "Algeria",                flag: "🇩🇿" },
  AR: { name: "Argentina",              flag: "🇦🇷" },
  AM: { name: "Armenia",                flag: "🇦🇲" },
  AU: { name: "Australia",              flag: "🇦🇺" },
  AT: { name: "Austria",                flag: "🇦🇹" },
  AZ: { name: "Azerbaijan",             flag: "🇦🇿" },
  BH: { name: "Bahrain",                flag: "🇧🇭" },
  BD: { name: "Bangladesh",             flag: "🇧🇩" },
  BY: { name: "Belarus",                flag: "🇧🇾" },
  BE: { name: "Belgium",                flag: "🇧🇪" },
  BO: { name: "Bolivia",                flag: "🇧🇴" },
  BA: { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  BR: { name: "Brazil",                 flag: "🇧🇷" },
  BG: { name: "Bulgaria",               flag: "🇧🇬" },
  KH: { name: "Cambodia",               flag: "🇰🇭" },
  CA: { name: "Canada",                 flag: "🇨🇦" },
  CL: { name: "Chile",                  flag: "🇨🇱" },
  CN: { name: "China",                  flag: "🇨🇳" },
  CO: { name: "Colombia",               flag: "🇨🇴" },
  HR: { name: "Croatia",                flag: "🇭🇷" },
  CU: { name: "Cuba",                   flag: "🇨🇺" },
  CZ: { name: "Czech Republic",         flag: "🇨🇿" },
  DK: { name: "Denmark",                flag: "🇩🇰" },
  EG: { name: "Egypt",                  flag: "🇪🇬" },
  ET: { name: "Ethiopia",               flag: "🇪🇹" },
  FI: { name: "Finland",                flag: "🇫🇮" },
  FR: { name: "France",                 flag: "🇫🇷" },
  GE: { name: "Georgia",                flag: "🇬🇪" },
  DE: { name: "Germany",                flag: "🇩🇪" },
  GH: { name: "Ghana",                  flag: "🇬🇭" },
  GR: { name: "Greece",                 flag: "🇬🇷" },
  GT: { name: "Guatemala",              flag: "🇬🇹" },
  HN: { name: "Honduras",               flag: "🇭🇳" },
  HK: { name: "Hong Kong",              flag: "🇭🇰" },
  HU: { name: "Hungary",                flag: "🇭🇺" },
  IS: { name: "Iceland",                flag: "🇮🇸" },
  IN: { name: "India",                  flag: "🇮🇳" },
  ID: { name: "Indonesia",              flag: "🇮🇩" },
  IR: { name: "Iran",                   flag: "🇮🇷" },
  IQ: { name: "Iraq",                   flag: "🇮🇶" },
  IE: { name: "Ireland",                flag: "🇮🇪" },
  IL: { name: "Israel",                 flag: "🇮🇱" },
  IT: { name: "Italy",                  flag: "🇮🇹" },
  JM: { name: "Jamaica",                flag: "🇯🇲" },
  JP: { name: "Japan",                  flag: "🇯🇵" },
  JO: { name: "Jordan",                 flag: "🇯🇴" },
  KZ: { name: "Kazakhstan",             flag: "🇰🇿" },
  KE: { name: "Kenya",                  flag: "🇰🇪" },
  KR: { name: "South Korea",            flag: "🇰🇷" },
  KW: { name: "Kuwait",                 flag: "🇰🇼" },
  LB: { name: "Lebanon",                flag: "🇱🇧" },
  LY: { name: "Libya",                  flag: "🇱🇾" },
  LT: { name: "Lithuania",              flag: "🇱🇹" },
  LU: { name: "Luxembourg",             flag: "🇱🇺" },
  MY: { name: "Malaysia",               flag: "🇲🇾" },
  MX: { name: "Mexico",                 flag: "🇲🇽" },
  MA: { name: "Morocco",                flag: "🇲🇦" },
  MM: { name: "Myanmar",                flag: "🇲🇲" },
  NL: { name: "Netherlands",            flag: "🇳🇱" },
  NZ: { name: "New Zealand",            flag: "🇳🇿" },
  NG: { name: "Nigeria",                flag: "🇳🇬" },
  NO: { name: "Norway",                 flag: "🇳🇴" },
  PK: { name: "Pakistan",               flag: "🇵🇰" },
  PS: { name: "Palestine",              flag: "🇵🇸" },
  PA: { name: "Panama",                 flag: "🇵🇦" },
  PE: { name: "Peru",                   flag: "🇵🇪" },
  PH: { name: "Philippines",            flag: "🇵🇭" },
  PL: { name: "Poland",                 flag: "🇵🇱" },
  PT: { name: "Portugal",               flag: "🇵🇹" },
  QA: { name: "Qatar",                  flag: "🇶🇦" },
  RO: { name: "Romania",                flag: "🇷🇴" },
  RU: { name: "Russia",                 flag: "🇷🇺" },
  SA: { name: "Saudi Arabia",           flag: "🇸🇦" },
  SN: { name: "Senegal",                flag: "🇸🇳" },
  RS: { name: "Serbia",                 flag: "🇷🇸" },
  SG: { name: "Singapore",              flag: "🇸🇬" },
  SK: { name: "Slovakia",               flag: "🇸🇰" },
  SI: { name: "Slovenia",               flag: "🇸🇮" },
  ZA: { name: "South Africa",           flag: "🇿🇦" },
  ES: { name: "Spain",                  flag: "🇪🇸" },
  LK: { name: "Sri Lanka",              flag: "🇱🇰" },
  SE: { name: "Sweden",                 flag: "🇸🇪" },
  CH: { name: "Switzerland",            flag: "🇨🇭" },
  SY: { name: "Syria",                  flag: "🇸🇾" },
  TW: { name: "Taiwan",                 flag: "🇹🇼" },
  TH: { name: "Thailand",               flag: "🇹🇭" },
  TN: { name: "Tunisia",                flag: "🇹🇳" },
  TR: { name: "Turkey",                 flag: "🇹🇷" },
  UA: { name: "Ukraine",                flag: "🇺🇦" },
  AE: { name: "United Arab Emirates",   flag: "🇦🇪" },
  GB: { name: "United Kingdom",         flag: "🇬🇧" },
  US: { name: "United States",          flag: "🇺🇸" },
  UY: { name: "Uruguay",                flag: "🇺🇾" },
  UZ: { name: "Uzbekistan",             flag: "🇺🇿" },
  VE: { name: "Venezuela",              flag: "🇻🇪" },
  VN: { name: "Vietnam",                flag: "🇻🇳" },
  YE: { name: "Yemen",                  flag: "🇾🇪" },
  ZW: { name: "Zimbabwe",               flag: "🇿🇼" },
};
